config/routes.rb
Household::Application.routes.draw do

  resources :texte_de_chats

  resources :chats

  resources :balance_utilisateurs

  get "balances/clore", to: "balances#clore", as: :clore_balance
  resources :balances

  resources :mouvement_recurrents

  resources :monnaies
  get "mouvements/new_paiements", to: "mouvements#new_paiements", as: :new_paiements
  get "mouvements/new_revenus", to: "mouvements#new_revenus", as: :new_revenus
  get "mouvements/edit_paiements", to: "mouvements#edit_paiements", as: :edit_paiements
  get "mouvements/edit_revenus", to: "mouvements#edit_revenus", as: :edit_revenus
  post "mouvements/create_mouvements", to: "mouvements#create_mouvements", as: :create_mouvements
  put "mouvements/update_mouvements", to: "mouvements#update_mouvements", as: :update_mouvements
  resources :mouvements


  resources :type_de_mouvements

  devise_for :utilisateurs

  get "/test", to: "test#index"
  root to: "home#index"
end

app/models/balance.rb
#encoding: utf-8
class Balance < ActiveRecord::Base
  attr_accessible :fini, :montant_cents, :nom, :montant
  monetize :montant_cents

  has_many :mouvements

  def recalculate!
    self.montant = Money.new(0)
    mouvements.where("pourcent_a_facturer_a_lautre > 0").each do |mouvement|
      if mouvement.payeur_id == 1
        self.montant += mouvement.montant * mouvement.pourcent_a_facturer_a_lautre / 100
      else
        self.montant -= mouvement.montant * mouvement.pourcent_a_facturer_a_lautre / 100
      end
    end
    self.update_attribute(:montant_cents, montant_cents)
  end


  def clore!
    Mouvement.where(fini: 0).update_all(fini: 1)
    self.nom = "Balance terminée le #{Date.today}"
    self.save
    Balance.create({nom: "Balance courante", fini: 0, montant_cents: 0}, without_protection: true)
  end

  def self.current
    Balance.where(fini: false).order("id desc").first
  end

  def montant_inverse
    montant.to_f - 2*montant.to_f
  end

end

app/controllers/balances_controller.rb
#encoding: utf-8

class BalancesController < ApplicationController
  # GET /balances
  # GET /balances.json
  def index
    @balances = Balance.order("fini DESC, id DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @balances }
    end
  end

  # GET /balances/1
  # GET /balances/1.json
  def show
    @balance = Balance.find(params[:id])
    @other_user = Utilisateur.where("id != ?", current_utilisateur.id).first
    @is_primary_user = true if current_utilisateur.id == 1
    @mouvements_main = Mouvement.where(payeur_id: current_utilisateur.id, revenu: false, balance_id: @balance.id).order("id DESC")
    @mouvements_second = Mouvement.where(payeur_id: @other_user, revenu: false, balance_id: @balance.id).order("id DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @balance }
    end
  end

  # GET /balances/new
  # GET /balances/new.json
  def new
    @balance = Balance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @balance }
    end
  end

  # GET /balances/1/edit
  def edit
    @balance = Balance.find(params[:id])
  end

  # POST /balances
  # POST /balances.json
  def create
    @balance = Balance.new(params[:balance])

    respond_to do |format|
      if @balance.save
        format.html { redirect_to @balance, notice: 'Balance was successfully created.' }
        format.json { render json: @balance, status: :created, location: @balance }
      else
        format.html { render action: "new" }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /balances/1
  # PUT /balances/1.json
  def update
    @balance = Balance.find(params[:id])

    respond_to do |format|
      if @balance.update_attributes(params[:balance])
        format.html { redirect_to @balance, notice: 'Balance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balances/1
  # DELETE /balances/1.json
  def destroy
    @balance = Balance.find(params[:id])
    @balance.destroy

    respond_to do |format|
      format.html { redirect_to balances_url }
      format.json { head :no_content }
    end
  end


  def clore
    Balance.current.clore!
    flash[:notice] = "Balance cloturée. Une nouvelle balance a été créée."
    redirect_to balances_path
  end
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/views/balances/_form.html.haml
= simple_form_for @balance, :html => { :class => 'form-horizontal' } do |f|
  = f.input :nom
  = f.input :montant
  = f.input :fini
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), balances_path, :class => 'btn'

app/views/balances/edit.html.haml
- model_class = Balance
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/balances/index.html.haml
- model_class = Balance
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:nom)
      %th= model_class.human_attribute_name(:montant)
      %th= model_class.human_attribute_name(:fini)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @balances.each do |balance|
      %tr
        %td= link_to balance.id, balance_path(balance)
        %td= balance.nom
        %td= balance.montant
        %td= balance.fini
        %td=l balance.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_balance_path(balance), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), balance_path(balance), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_balance_path, :class => 'btn btn-primary'
= link_to "Clore la balance", clore_balance_path, :class => 'btn btn-danger', data: {confirm: "Une nouvelle balance sera créée"}

app/views/balances/new.html.haml
- model_class = Balance
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/balances/show.html.haml
- model_class = Balance
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:nom) + ':'
  %br
  = @balance.nom
%p
  %strong= model_class.human_attribute_name(:montant) + ':'
  %br
  = @balance.montant
%p
  %strong= model_class.human_attribute_name(:fini) + ':'
  %br
  = @balance.fini

- @model_class = Mouvement
= render 'mouvements/one_user_paiements', user: current_utilisateur, mouvements: @mouvements_main, no_action: true
.page-header
  &nbsp;
= render 'mouvements/one_user_paiements', user: @other_user, mouvements: @mouvements_second, no_action: true