config/routes.rb
Household::Application.routes.draw do

  resources :texte_de_chats

  resources :chats

  resources :balance_utilisateurs

  get "balances/clore", to: "balances#clore", as: :clore_balance
  resources :balances

  resources :mouvement_recurrents

  resources :monnaies
  get "mouvements/new_paiements", to: "mouvements#new_paiements", as: :new_paiements
  get "mouvements/new_revenus", to: "mouvements#new_revenus", as: :new_revenus
  get "mouvements/edit_paiements", to: "mouvements#edit_paiements", as: :edit_paiements
  get "mouvements/edit_revenus", to: "mouvements#edit_revenus", as: :edit_revenus
  post "mouvements/create_mouvements", to: "mouvements#create_mouvements", as: :create_mouvements
  put "mouvements/update_mouvements", to: "mouvements#update_mouvements", as: :update_mouvements
  resources :mouvements


  resources :type_de_mouvements

  devise_for :utilisateurs

  get "/test", to: "test#index"
  root to: "home#index"
end

app/models/balance_utilisateur.rb
class BalanceUtilisateur < ActiveRecord::Base
  belongs_to :utilisateur
  attr_accessible :annee, :mois, :montant_cents, :utilisateur_id

  monetize :montant_cents
end

app/controllers/balance_utilisateurs_controller.rb
class BalanceUtilisateursController < ApplicationController
  # GET /balance_utilisateurs
  # GET /balance_utilisateurs.json
  def index
    @balance_utilisateurs = BalanceUtilisateur.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @balance_utilisateurs }
    end
  end

  # GET /balance_utilisateurs/1
  # GET /balance_utilisateurs/1.json
  def show
    @balance_utilisateur = BalanceUtilisateur.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @balance_utilisateur }
    end
  end

  # GET /balance_utilisateurs/new
  # GET /balance_utilisateurs/new.json
  def new
    @balance_utilisateur = BalanceUtilisateur.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @balance_utilisateur }
    end
  end

  # GET /balance_utilisateurs/1/edit
  def edit
    @balance_utilisateur = BalanceUtilisateur.find(params[:id])
  end

  # POST /balance_utilisateurs
  # POST /balance_utilisateurs.json
  def create
    @balance_utilisateur = BalanceUtilisateur.new(params[:balance_utilisateur])

    respond_to do |format|
      if @balance_utilisateur.save
        format.html { redirect_to @balance_utilisateur, notice: 'Balance utilisateur was successfully created.' }
        format.json { render json: @balance_utilisateur, status: :created, location: @balance_utilisateur }
      else
        format.html { render action: "new" }
        format.json { render json: @balance_utilisateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /balance_utilisateurs/1
  # PUT /balance_utilisateurs/1.json
  def update
    @balance_utilisateur = BalanceUtilisateur.find(params[:id])

    respond_to do |format|
      if @balance_utilisateur.update_attributes(params[:balance_utilisateur])
        format.html { redirect_to @balance_utilisateur, notice: 'Balance utilisateur was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @balance_utilisateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balance_utilisateurs/1
  # DELETE /balance_utilisateurs/1.json
  def destroy
    @balance_utilisateur = BalanceUtilisateur.find(params[:id])
    @balance_utilisateur.destroy

    respond_to do |format|
      format.html { redirect_to balance_utilisateurs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/balance_utilisateurs_helper.rb
module BalanceUtilisateursHelper
end

app/views/balance_utilisateurs/_form.html.haml
= simple_form_for @balance_utilisateur, :html => { :class => 'form-horizontal' } do |f|
  = f.association :utilisateur
  = f.input :montant
  = f.input :mois
  = f.input :annee
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), balance_utilisateurs_path, :class => 'btn'

app/views/balance_utilisateurs/edit.html.haml
- model_class = BalanceUtilisateur
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/balance_utilisateurs/index.html.haml
- model_class = BalanceUtilisateur
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:utilisateur_id)
      %th= model_class.human_attribute_name(:montant)
      %th= model_class.human_attribute_name(:mois)
      %th= model_class.human_attribute_name(:annee)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @balance_utilisateurs.each do |balance_utilisateur|
      %tr
        %td= link_to balance_utilisateur.id, balance_utilisateur_path(balance_utilisateur)
        %td= balance_utilisateur.utilisateur.name
        %td= balance_utilisateur.montant
        %td= balance_utilisateur.mois
        %td= balance_utilisateur.annee
        %td=l balance_utilisateur.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_balance_utilisateur_path(balance_utilisateur), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), balance_utilisateur_path(balance_utilisateur), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_balance_utilisateur_path, :class => 'btn btn-primary'

app/views/balance_utilisateurs/new.html.haml
- model_class = BalanceUtilisateur
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/balance_utilisateurs/show.html.haml
- model_class = BalanceUtilisateur
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:utilisateur_id) + ':'
  %br
  = @balance_utilisateur.utilisateur.name
%p
  %strong= model_class.human_attribute_name(:montant_cents) + ':'
  %br
  = @balance_utilisateur.montant
%p
  %strong= model_class.human_attribute_name(:mois) + ':'
  %br
  = @balance_utilisateur.mois
%p
  %strong= model_class.human_attribute_name(:annee) + ':'
  %br
  = @balance_utilisateur.annee

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), balance_utilisateurs_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_balance_utilisateur_path(@balance_utilisateur), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), balance_utilisateur_path(@balance_utilisateur), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'