config/routes.rb
Household::Application.routes.draw do

  resources :texte_de_chats

  resources :chats

  resources :balance_utilisateurs

  get "balances/clore", to: "balances#clore", as: :clore_balance
  resources :balances

  resources :mouvement_recurrents

  resources :monnaies
  get "mouvements/new_paiements", to: "mouvements#new_paiements", as: :new_paiements
  get "mouvements/new_revenus", to: "mouvements#new_revenus", as: :new_revenus
  get "mouvements/edit_paiements", to: "mouvements#edit_paiements", as: :edit_paiements
  get "mouvements/edit_revenus", to: "mouvements#edit_revenus", as: :edit_revenus
  post "mouvements/create_mouvements", to: "mouvements#create_mouvements", as: :create_mouvements
  put "mouvements/update_mouvements", to: "mouvements#update_mouvements", as: :update_mouvements
  resources :mouvements


  resources :type_de_mouvements

  devise_for :utilisateurs

  get "/test", to: "test#index"
  root to: "home#index"
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
- if !get_form_object_errors.empty?
  - get_form_object_errors.full_messages.each_with_index do |msg, index|
    .alert.alert-error
      %a.close{"data-dismiss" => "alert"} &#215;
      = content_tag :div, "#{msg}", :id => "flash_#{index}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Gestion AA et CR + Chats"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Gestion AA et CR (+ les chats)
          .container.nav-collapse
            %ul.nav
              %li= link_to "Ajout de paiements", :new_paiements
              %li= link_to "Consulter les paiements", :edit_paiements
              %li= link_to "Ajout de revenus", :new_revenus
              %li= link_to "Consulter les revenus", :edit_revenus

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Navigation
              %li= link_to "Textes des chats", texte_de_chats_path
              %li= link_to "Chats", chats_path
              %li= link_to "Mouvements", mouvements_path
              %li= link_to "Balances", balances_path
              %li= link_to "Mouvements récurrents", mouvement_recurrents_path
              %li= link_to "Type de mouvements", type_de_mouvements_path
              %li= link_to "Monnaies", monnaies_path
              %li= link_to "Log out", destroy_utilisateur_session_path, method: "DELETE"
        .span9

          = render 'layouts/messages'
          = yield
    
      %footer
        %p &copy;  Anthony ze best developer of ze world 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/guest.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Gestion AA et CR + Chats"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Gestion AA et CR (+ les chats)
          .container.nav-collapse


    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Navigation
        .span9

          = yield
    
      %footer
        %p &copy;  Anthony ze best developer of ze world 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"