config/routes.rb
Household::Application.routes.draw do

  resources :texte_de_chats

  resources :chats

  resources :balance_utilisateurs

  get "balances/clore", to: "balances#clore", as: :clore_balance
  resources :balances

  resources :mouvement_recurrents

  resources :monnaies
  get "mouvements/new_paiements", to: "mouvements#new_paiements", as: :new_paiements
  get "mouvements/new_revenus", to: "mouvements#new_revenus", as: :new_revenus
  get "mouvements/edit_paiements", to: "mouvements#edit_paiements", as: :edit_paiements
  get "mouvements/edit_revenus", to: "mouvements#edit_revenus", as: :edit_revenus
  post "mouvements/create_mouvements", to: "mouvements#create_mouvements", as: :create_mouvements
  put "mouvements/update_mouvements", to: "mouvements#update_mouvements", as: :update_mouvements
  resources :mouvements


  resources :type_de_mouvements

  devise_for :utilisateurs

  get "/test", to: "test#index"
  root to: "home#index"
end

app/models/mouvement.rb
class Mouvement < ActiveRecord::Base
  belongs_to :payeur, class_name: "Utilisateur"
  belongs_to :type_de_mouvement
  belongs_to :balance
  attr_accessible :fini, :montant, :pourcent_a_facturer_a_lautre, :texte, :payeur_id, :type_de_mouvement_id, :montant_cents, :revenu, :balance_id, :pourcent_a_facturer_a_lautre

  validates :montant, :pourcent_a_facturer_a_lautre, :payeur, :type_de_mouvement, :balance, presence: true

  monetize :montant_cents

  validates :montant, numericality: {greater_than: 0}

  after_create :impact_balance
  before_validation :set_balance
  before_save :set_percentage


  def self.frequences
    %W{\  toutes_les_deux_semaines une_fois_par_mois une_fois_tous_les_deux_mois}
  end

  private

  def impact_balance

    if pourcent_a_facturer_a_lautre > 0 && !revenu
      montant_a_balancer = montant * pourcent_a_facturer_a_lautre / 100
      if payeur_id == 1
        balance.montant += montant_a_balancer
      else
        balance.montant -= montant_a_balancer
      end
      balance.save
    end

  end

  def set_balance
    Rails.logger.error("IN SET BALANCE")
    self.balance_id = Balance.current.id if new_record?
    Rails.logger.error("IN SET BALANCE #{balance_id}")
  end

  def set_percentage
    if revenu?
      self.pourcent_a_facturer_a_lautre = 0
    end
  end
end

app/controllers/mouvements_controller.rb
class MouvementsController < ApplicationController
  # GET /mouvements
  # GET /mouvements.json
  def index
    @mouvements = Mouvement.order("fini DESC, id DESC").page(params[:page]).per(100)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mouvements }
    end
  end

  # GET /mouvements/1
  # GET /mouvements/1.json
  def show
    @mouvement = Mouvement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mouvement }
    end
  end

  # GET /mouvements/new
  # GET /mouvements/new.json
  def new
    @mouvement = Mouvement.new(payeur_id: current_utilisateur.id, pourcent_a_facturer_a_lautre: current_utilisateur.default_pourcent_a_facturer_a_lautre)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mouvement }
    end
  end

  # GET /mouvements/1/edit
  def edit
    @mouvement = Mouvement.find(params[:id])
  end

  # POST /mouvements
  # POST /mouvements.json
  def create
    @mouvement = Mouvement.new(params[:mouvement])

    respond_to do |format|
      if @mouvement.save
        format.html { redirect_to @mouvement, notice: 'Mouvement was successfully created.' }
        format.json { render json: @mouvement, status: :created, location: @mouvement }
      else
        format.html { render action: "new" }
        format.json { render json: @mouvement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mouvements/1
  # PUT /mouvements/1.json
  def update
    @mouvement = Mouvement.find(params[:id])

    respond_to do |format|
      if @mouvement.update_attributes(params[:mouvement])
        Balance.current.recalculate!
        format.html { redirect_to @mouvement, notice: 'Mouvement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mouvement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mouvements/1
  # DELETE /mouvements/1.json
  def destroy
    @mouvement = Mouvement.find(params[:id])
    @mouvement.destroy
    Balance.current.recalculate!
    flash[:notice] = "Supprime avec succes"

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  def new_paiements
    @mouvements = []
    30.times do
      @mouvements << Mouvement.new(payeur_id: current_utilisateur.id, pourcent_a_facturer_a_lautre: current_utilisateur.default_pourcent_a_facturer_a_lautre)
    end
    @title = "Nouveaux paiements"
    @form_url = create_mouvements_path
    @revenu = false
    @mode = "new"
    render action: :mouvements
  end

  def new_revenus
    @mouvements = []
    30.times do
      @mouvements << Mouvement.new(payeur_id: current_utilisateur.id, revenu: true)
    end
    @title = "Nouveaux revenus"
    @revenu = true
    @form_url = create_mouvements_path
    @mode = "new"
    render action: :mouvements
  end

  def edit_paiements
    @other_user = Utilisateur.where("id != ?", current_utilisateur.id).first
    @mouvements_main = Mouvement.where(payeur_id: current_utilisateur.id, revenu: false, fini: 0).order("id DESC")
    @mouvements_second = Mouvement.where(payeur_id: @other_user, revenu: false, fini: 0).order("id DESC")
    @balance = Balance.current
    @is_primary_user = true if current_utilisateur.id == 1

    if @is_primary_user
      @left_user = @other_user
      @right_user = current_utilisateur
    else
      @left_user = current_utilisateur
      @right_user = @other_user
    end


  end

  def edit_revenus
    @mouvements = Mouvement.where(payeur_id: current_utilisateur.id, revenu: true).order("id DESC")
    @title = "Revenus"
    @revenu = true
    @form_url = update_mouvements_path
    @mode = "edit"
    render action: :mouvements
  end

  def create_mouvements
    #begin
    params[:mouvements].each do |mouvement|
      next if mouvement[:montant].blank? || mouvement[:type_de_mouvement_id].blank?
      Mouvement.create(mouvement)
    end

    if params[:revenu] == "true"
      redirect_to :edit_revenus, notice: 'Succes, les nouveaux revenus ont ete ajoute a la liste ci-dessous'
    else
      redirect_to :edit_paiements, notice: 'Succes, les nouveaux paiements ont ete ajoute a la liste ci-dessous'
    end


  end

  def update_mouvements
    #params[:mouvements].each do |mouvement|
      #next if mouvement[:montant].blank? || mouvement[:type_de_mouvement_id].blank?
      Mouvement.update(params[:mouvements].keys, params[:mouvements].values)
    #end
    Balance.current.recalculate!
    redirect_to :edit_paiements, notice: 'Succes, les paiements ont ete modifies'
  end


end

app/helpers/mouvements_helper.rb
module MouvementsHelper
end

app/views/mouvements/_form.html.haml
= simple_form_for @mouvement, :html => { :class => 'form-horizontal' } do |f|
  = f.association :payeur, :prompt => "Choisir"
  = f.input :montant
  = f.association :type_de_mouvement, label_method: :nom, :prompt => "Choisir"
  = f.input :fini
  = f.input :revenu
  = f.input :pourcent_a_facturer_a_lautre

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), mouvements_path, :class => 'btn'

app/views/mouvements/_one_user_paiements.html.haml
- no_action = local_assigns[:no_action] || false

%h3= "Paiements de #{user.name}, pour un total de #{humanized_money_with_symbol(sum_montants(mouvements))}"
%table.table.table-striped.table_form.half_table
  %thead
    %tr
      %th= @model_class.human_attribute_name(:montant)
      %th Type
      %th= @model_class.human_attribute_name(:pourcent_a_facturer_a_lautre)
      %th= @model_class.human_attribute_name(:payeur_id)
      %th Commentaire
      %th Date
      - unless no_action
        %th Action
  %tbody
    - mouvements.each do |mouvement|
      = fields_for "mouvements[]", mouvement do |f|
        = f.hidden_field :revenu
        %tr
          %td= f.text_field :montant, disabled: no_action
          %td= f.collection_select :type_de_mouvement_id, TypeDeMouvement.where(revenu: false), :id, :nom, { :prompt => "Choisir" } , disabled: no_action
          %td= f.number_field :pourcent_a_facturer_a_lautre, disabled: no_action
          %td= f.collection_select :payeur_id, Utilisateur.all, :id, :name, { :prompt => "Choisir" }, disabled: no_action
          %td= f.text_field :texte, disabled: no_action
          %td= l(mouvement.created_at)
          %td= link_to t('.destroy', :default => t("helpers.links.destroy")), mouvement_path(mouvement), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger' unless no_action

app/views/mouvements/edit.html.haml
- model_class = Mouvement
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/mouvements/edit_paiements.html.haml
- @model_class = Mouvement
.page-header


  %h2
    - if @balance.montant > 0
      = "Actuellement, #{image_tag(@left_user.gravatar_url).html_safe} #{@left_user.name}  doit #{humanized_money_with_symbol @balance.montant} à #{image_tag(@right_user.gravatar_url).html_safe} #{@right_user.name}".html_safe
    - elsif @balance.montant < 0
      = "Actuellement, #{image_tag(@right_user.gravatar_url).html_safe} #{@right_user.name} doit #{humanized_money_with_symbol @balance.montant_inverse} à #{image_tag(@left_user.gravatar_url).html_safe} #{@left_user.name}".html_safe
    - else
      = "Actuellement, les comptes sont à l'equilibre. #{image_tag(@left_user.gravatar_url).html_safe} <3 #{image_tag(@right_user.gravatar_url).html_safe}".html_safe


= form_tag update_mouvements_path, method: "put" do
  = hidden_field_tag "revenu", false
  = render 'one_user_paiements', user: current_utilisateur, mouvements: @mouvements_main
  .page-header
    &nbsp;
  = render 'one_user_paiements', user: @other_user, mouvements: @mouvements_second

  = submit_tag "Submit", :class => 'btn btn-primary'

app/views/mouvements/index.html.haml
- model_class = Mouvement
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
= paginate @mouvements
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:payeur_id)
      %th= model_class.human_attribute_name(:texte)
      %th= model_class.human_attribute_name(:montant)
      %th= model_class.human_attribute_name(:type_de_mouvement)
      %th= model_class.human_attribute_name(:fini)
      %th= model_class.human_attribute_name(:revenu)
      %th= model_class.human_attribute_name(:pourcent_a_facturer_a_lautre)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @mouvements.each do |mouvement|
      %tr
        %td= link_to mouvement.id, mouvement_path(mouvement)
        %td
          = mouvement.payeur.name
          = image_tag mouvement.payeur.gravatar_url, width:50, height:50

        %td= mouvement.texte
        %td= mouvement.montant
        %td
          = mouvement.type_de_mouvement.nom
          = image_tag mouvement.type_de_mouvement.image.url(:thumb)
        %td= mouvement.fini
        %td= mouvement.revenu
        %td= mouvement.pourcent_a_facturer_a_lautre
        %td=l mouvement.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_mouvement_path(mouvement), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), mouvement_path(mouvement), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_mouvement_path, :class => 'btn btn-primary'

app/views/mouvements/mouvements.html.haml
- model_class = Mouvement
.page-header
  %h1= @title
= form_tag @form_url do
  = hidden_field_tag "revenu", @revenu
  %table.table.table-striped.table_form
    %thead
      %tr
        %th= model_class.human_attribute_name(:montant)
        %th Type
        - if !@revenu
          %th= model_class.human_attribute_name(:pourcent_a_facturer_a_lautre)
        %th= model_class.human_attribute_name(:payeur_id)
        %th Commentaire
        - if @mode == "edit"
          %th Date
          %th Action
    %tbody
      - @mouvements.each do |mouvement|
        = fields_for "mouvements[]", mouvement do |f|
          = f.hidden_field :revenu
          %tr
            %td= f.text_field :montant
            %td= f.collection_select :type_de_mouvement_id, TypeDeMouvement.where(revenu: @revenu), :id, :nom, :prompt => "Choisir"
            - if !@revenu
              %td= f.number_field :pourcent_a_facturer_a_lautre
            %td= f.collection_select :payeur_id, Utilisateur.all, :id, :name, :prompt => "Choisir"
            %td= f.text_field :texte
            - if @mode == "edit"
              %td= l(mouvement.created_at)
              %td
                = link_to t('.destroy', :default => t("helpers.links.destroy")), mouvement_path(mouvement), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

  = submit_tag "Submit", :class => 'btn btn-primary'

app/views/mouvements/new.html.haml
- model_class = Mouvement
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/mouvements/show.html.haml
- model_class = Mouvement
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:payeur_id) + ':'
  %br
  = @mouvement.payeur_id
%p
  %strong= model_class.human_attribute_name(:texte) + ':'
  %br
  = @mouvement.texte
%p
  %strong= model_class.human_attribute_name(:montant) + ':'
  %br
  = @mouvement.montant
%p
  %strong= model_class.human_attribute_name(:type_de_mouvement_id) + ':'
  %br
  = @mouvement.type_de_mouvement_id
%p
  %strong= model_class.human_attribute_name(:fini) + ':'
  %br
  = @mouvement.fini
%p
  %strong= model_class.human_attribute_name(:revenu) + ':'
  %br
  = @mouvement.revenu
%p
  %strong= model_class.human_attribute_name(:pourcent_a_facturer_a_lautre) + ':'
  %br
  = @mouvement.pourcent_a_facturer_a_lautre

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), mouvements_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_mouvement_path(@mouvement), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), mouvement_path(@mouvement), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'